version: '3.8'
services:
  database:
    build:
      context: ./services/database
      dockerfile: Dockerfile
    container_name: database_container
    ports:
      - '5432:5432'

  scraper:
    build:
      context: ./services/scraper
      dockerfile: Dockerfile
    container_name: scraper_container
    ports:
      - '6000:6000'
    volumes:
      - ./services/scraper:/scraper
      - ./services/scraper/nodemon.json:/scraper/nodemon.json
      - /scraper/node_modules
    depends_on:
      - database

  websocket:
    build:
      context: ./services/websocket
      dockerfile: Dockerfile
    container_name: websocket_container
    ports:
      - '8000:8000'
    volumes:
      - ./services/websocket:/websocket
      - ./services/websocket/nodemon.json:/websocket/nodemon.json
      - /websocket/node_modules
    depends_on:
      - database
      - scraper

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - '4000:4000'
    stdin_open: true
    tty: true
    depends_on:
      - websocket
      - database
